- functions.php
- template-parts/archive.php
- template-parts/header.php
- template-parts/single.php
Added missing Classes and function calls.
removed deregister core scripts
currently Theme check return:
* WARNING: .gitignore .git Hidden Files or Folders found.
* REQUIRED: Your Theme URI and Author URI should not be the same.
* REQUIRED: Please remove any extraneous directories like .git or .svn from the ZIP file before uploading it.
* RECOMMENDED: Screenshot size should be 1200x900, to account for HiDPI displays. Any 4:3 image size is acceptable, but 1200x900 is preferred.
* RECOMMENDED: No reference to add_theme_support( "custom-header", $args ) was found in the theme. It is recommended that the theme implement this functionality if using an image for the header.
RECOMMENDED: No reference to add_theme_support( "custom-background", $args ) was found in the theme. If the theme uses …
> Modifications to match WordPress Repo guidelines

- README.md
- readme.txt
- template-parts/single.php
Remove tags: `flexible-header` and `custom-colors`.
> Per TRT remarks: add nextpage support to single.php

- assets/scss/reset/_forms.scss
Fix Comments form BUG.
See: #109
> Add reset rules to `input[type="url"]`

- includes/admin-functions.php
- includes/customizer-functions.php
Fix: OBXT-169 add customizer settings sanitization
Fix: OBXT-170 escape theme_direcory_uri
> 2.4.0 Release fixes

- assets/scss/theme/_navigation.scss
- template-parts/footer.php
Tweak: Updated accessibility for nav menus, sub-menus now support tabbing with keyboard controls
Tweak: Added support for the footer menu on sites that are not running Elementor
> Accessibility Fixes [ED-6298]

- includes/admin-functions.php
- includes/customizer/elementor-upsell.php
- phpcs.xml
- template-parts/dynamic-footer.php
- template-parts/dynamic-header.php
- template-parts/footer.php
- template-parts/header.php
Fixed: https://github.com/elementor/hello-theme/issues/194
> Tweak: Add output escaping

- template-parts/single.php
> Tweak: Remove unnecessary PHP tags

- assets/dev/js/frontend/hello-frontend.js
> Tweak: Toggle mobile menu with Enter & Space keyboard keys [ED-9463]

- assets/scss/editor.scss
> Tweak: Match CSS to the new Elementor Editor Facelift [ED-10093]

- header.php
We hardcode the skip link in the theme.
We should add filter to enable/disable skip link and a filter to change skip link URL.
**Related Issues:**
https://github.com/elementor/hello-theme/issues/217 
https://github.com/elementor/elementor/issues/9292 
https://github.com/elementor/elementor/issues/17433 
https://github.com/elementor/elementor/issues/19215
> Tweak: Add filter to enable/disable skip link and a filter to change skip link URL [ED-10179]

- functions.php
Fixes: https://github.com/elementor/hello-theme/issues/278
> Fix: Child themes using `hello_elementor_body_open()` no longer working [ED-10258]

- includes/customizer/elementor-upsell.php
The theme has 2 similar translation strings that can should be merged to one string.
> Tweak: Merge similar translation strings (i18n) [ED-10556]

- assets/dev/js/admin/pages/main-page.js
- assets/dev/js/admin/pages/panels/rss-feeds.js
- assets/dev/js/admin/pages/settings.js
- includes/settings-functions.php
> Tweak: Theme settings page [ED-11811]

- includes/settings-functions.php
> Tweak: Add a settings page to Hello theme [ED-11811]

- readme.txt
- template-parts/dynamic-footer.php
- template-parts/dynamic-header.php
- template-parts/footer.php
- template-parts/header.php
> Tweak: Remove unnecessary `role` attributes from HTML landmark elements

- functions.php
- includes/elementor-functions.php
Fix some issues after https://github.com/elementor/hello-theme/pull/341
> Tweak: Move header-footer styles to a separate CSS file [ED-12687]

- template-parts/single.php
Fixes: https://github.com/elementor/hello-theme/issues/304
> Fix: Separate post tags in single post [ED-13992]

- assets/scss/reset/_table.scss
Fixes: https://github.com/elementor/hello-theme/issues/311
> Fix: Remove duplicate table styles [ED-13991]

- assets/scss/editor-styles.scss
- functions.php
- theme.json
Fix: https://github.com/elementor/hello-theme/issues/430
> Fix: Gutenberg editor expanded disproportionately after adding support for `theme.json` [ED-16428]

- package-lock.json
`npx update-browserslist-db@latest`
> Update browsers list db to latest version

- .browserslistrc
Match Hello theme to Elementor.
Ref: https://github.com/elementor/elementor/pull/29008
> Update browsers list

- includes/settings/settings-footer.php
- includes/settings/settings-header.php
> Site Settings: tweaking upsell copy and button for Header and Footer [TMZ-511]

- includes/customizer/customizer-action-links.php
- includes/utils.php
- modules/admin-home/rest/admin-config.php
depending on whether Elementor is already installed or not
> TMZ-568 - Install Elementor CTA text

- modules/admin-home/rest/promotions.php
> [TMZ-660] Fix pro banner behavior

- functions.php
Purpose: Update editor style path in Hello Elementor theme to use assets directory structure.
Main changes:
- Changed editor stylesheet path from 'editor-styles.css' to 'assets/css/editor-styles.css'
> Fixes the path to the `editor-styles.css` [TMZ-707] (#499)

- .github/workflows/cherry-pick-pr.yml
Purpose: Add test comment to cherry-pick PR workflow for documentation and future implementation purposes.
Main changes:
- Added explanatory comment to the GitHub workflow file for cherry-picking merged PRs
> Internal: Add a test comment [TMZ-799]

- .github/workflows/playwright-with-specific-elementor-version.yml
Purpose: Refactor Hello Theme version handling workflow to simplify version selection process and remove complex Git operations.
Main changes:
- Removed complex Git checkout/restore mechanism for version management
- Added improved version detection and source tracking outputs
- Simplified artifact naming with more meaningful identifiers
- Eliminated unnecessary backup cleanup steps
> Internal: Update Elementor download method [TMZ-905]

- functions.php
- package-lock.json
- package.json
- readme.txt
- style.css
Purpose: Update Hello Elementor theme version from 3.4.4 to 3.4.5 across all configuration files to prepare for release.
Main changes:
- Bumped version number from 3.4.4 to 3.4.5 in functions.php definition
- Updated version and stable tag to 3.4.5 in style.css theme metadata
- Changed package version to 3.4.5 in package.json configuration file
> Internal: Bump version and add changelog [TMZ-954]
