assets/scss/reset/_wordpress.scss
wp images alignment fix: 
When we have img.alignleft margin should be on the right and vice-versa for img.alignright.
=> CSS: Fix - WP image margin

Gruntfile.js
There is a conflict when you try to add css animations in the theme.
cssnano in Gulp renames the animations and they broke. 
I found that other developers had the same problem with the minifier, I found the solution to it and apply it to gulpfile.js. The solution is in this closed issue from cssnano github: https://github.com/cssnano/cssnano/issues/247
=> Fixed conflicts with minifier cssnano and css animations

assets/scss/theme/_general.scss
Removing center text for captions by default allows the Elementor Image Widget to control the alignment of the image and caption without needing to set an explicit alignment for the caption. Solves elementor/elementor#10003
=> Remove caption centering by default

assets/scss/reset/_reset.scss
Props: https://wordpress.org/support/topic/no-font-smoothing-in-hello/
=> Add font smoothing

editor-style.css, editor-style.min.css
There's some strangeness in the editor styles. There's redundant code, styles that override styles that were just set, and most importantly, a really terrible font choice for code-related elements. I've fixed these.
=> Fixed font weirdness in editor-style.css

assets/scss/theme/_general.scss, functions.php
Images 3 align options right/center/left. Gutenberg introduced 2 new alignment options (wide/full).
Themes must support them with `add_theme_support( 'align-wide' )` in `functions.php` file. They also need to add custom CSS.
This will add to the block editor the two new align options:
**Wide alignment:**
**Full alignment:**
This PR added wide/full images support to Elementor Hello Theme.
=> Add theme support for Gutenberg wide/full images

functions.php, includes/admin-functions.php, includes/elementor-functions.php, includes/settings/settings-footer.php
Removed "theme switching" and "update transient" based hooks for determining whether the Header/Footer experiment should be active by default or not.
Instead, The experiment will be disabled by default if the user updated Hello Theme before installing Elementor v3.3.0. If Elementor v2.4.1 will be installed while Elementor 3.3.0 and up is installed, it will be active by default. Otherwise, it will be inactive by default.
=> Removed "theme switching", "update transient" hook callbacks, replaced by Elementor Experiments flag [ED-4050]

template-parts/archive.php
For better or worse, html tags are allowed in the WP post title field. If a user inputs html into the title field then it should be OK to allow the html to render (instead of displaying escaped html tags)
A screenshot before adding this tweak:
and after:
=> Archive template: Sanitize content for allowed HTML tags in post title 

functions.php, header.php
`wp_body_open()` was added in WordPress 5.2.
If the theme has a [minimum required versions of WordPress 5.3](https://github.com/elementor/hello-theme/pull/245), we no longer need the backwards compatibility functionality.
=> Tweak: Remove backwards compatibility support for `wp_body_open()` [ED-9469]

README.md, readme.txt
=> Tweak: Update minimum required WordPress version to 5.9 [ED-9466]

template-parts/archive.php, template-parts/search.php
The theme has to check if a features images was set.
Why? because currently it the there is no featured image, the markup prints an empty link:
Empty link without and image bloats the markup.
In addition, it creates an a11y issue as with keyboard navigation, we have another link (empty link).
=> Tweak: Check if posts have featured images set [ED-10057]

template-parts/dynamic-header.php
The dynamic header menu assumes Elementor plugin is installed and uses the `.elementor-screen-only` CSS class.
It should not assume the plugin installed, and use the `.screen-reader-text` CSS class which is already defined in the theme.
=> Tweak: Use theme CSS not Elementor plugins CSS [ED-10058]

Gruntfile.js
Elementor uses the following autoprefixer settings:
```
last 3 versions
not dead
```
While Hello theme uses only:
```
last 3 versions
```
We should match the settings.
=> Tweak: Match autoprefixer browsers list settings to Elementor plugin [ED-10094]

functions.php
The `functions.php` file has 6 deprecated filter hooks which were renamed in version 2.0 (release on 2019-05-12), almost 4 years ago.
It is time to delete the deprecated filter hooks.
=> Tweak: Delete filter hooks deprecated in version 2.0 [ED-10185]

includes/settings/settings-footer.php, includes/settings/settings-header.php
The theme adds Header & Footer panels to Elementor site settings where the user can change the style.
Some `Slider` controls should be extended to support all the available units and the `custom` unit.
=> Tweak: Added additional and `custom` units to header & footer panels [ED-10223]

includes/settings/settings-footer.php, includes/settings/settings-header.php
Hello Theme adds Header and Footer setting to the “Site Settings” panel.
The panels link to WordPress Customizer to allow the user to update the site title, tagline and logo.
It should link to Elementor “Site Identity” panel instead.
=> Tweak: Link to Elementor "Site Identity" panel from the header & footer panels [ED-10224]

README.md, functions.php, readme.txt
In the past WordPress themes/plugins included the translation files (`*.po` & `*.mo`) in the `languages` folder.
WordPress moved all the translations files to [translate.wordpress.org](http://translate.wordpress.org/) to simplify the translation process.
The Hello theme no longer need to call the `load_theme_textdomain()` function to load the translation files from the them folder. Besides, we load PO and MO files from the languages folder, but there are no PO and MO files there.
We can safely delete the `hello_elementor_load_textdomain` filter hook and the `load_theme_textdomain()` function it activates.
=> Tweak: Delete `hello_elementor_load_textdomain` filter hook [ED-10229]

assets/scss/reset/_reset.scss
The theme uses the following legacy CSS properties:
* `page-break-inside`
* `page-break-after`
They were replaced with newer CSS properties:
* `break-inside`
* `break-after`
=> Tweak: Replace legacy `page-break-*` CSS properties with `break-*` properties [ED-10559]

assets/scss/reset/_reset.scss
The theme has two similar CSS classes:
* `.sr-only` - not in use.
* `.screen-reader-text` - used in skip links and menu toggle button.
The second one is a modern classes using the latest best practices. We should delete the first, unused, class.
=> Tweak: Remove duplicate CSS classes for screen readers [ED-10558]

assets/scss/style.scss, readme.txt
Currently, the theme tested up to WordPress 6.4, but WordPress 6.5 already released. We need to update.
=> Tweak: Update `Tested up to 6.5` [ED-14565]

includes/settings/settings-footer.php, includes/settings/settings-header.php
Increase the design capability by introducing new style controls to Hello Theme Header & Footer.
New controls:
* New “Hover Color” and “Transition Duration” controls for site title (it’s a link).
* New “Text Shadow” controls for site title, tagline, menu and copyright.
* New “Text Stroke” control for site title.
In addition:
* All “RAW_HTML” controls replaced with the new “ALERT“ control for consistent design.
=> Tweak: Added new design options to header/footer [ED-16342]

.github/workflows/playwright.yml, package-lock.json, package.json, tests/wp-env/config/setup.sh
Purpose: Add missing build command and environment setup scripts for WordPress theme testing workflow.
Main changes:
- Fixed theme activation command from 'hello-elementor' to 'hello-theme' in setup script
- Added 'build:prod' step in GitHub workflow for plugin compilation before tests
- Added wp-env commands to package.json and included @wordpress/env dependency
=> Internal: Add missing command [TMZ-733]

.github/workflows/daily-test-matrix.yml, modules/admin-home/rest/admin-config.php
Purpose: Update daily test reporting and configuration for improved version tracking and UI links in the admin panel.
Main changes:
- Simplified site identity tab links by removing unnecessary parameters
- Added (GA) label to version numbers in test matrix combinations for clarity
- Implemented version display preservation for better test reporting
- Fixed delay scheduling for test combinations to prevent overlap
=> Internal: Update daily test report [TMZ-905]

.github/workflows/playwright-with-specific-elementor-version.yml
Purpose: Revert to standard Playwright test commands for Daily Matrix workflow by removing custom configuration.
Main changes:
- Replaced custom Playwright daily matrix config with standard npm test command for regular tests
- Updated tagged tests execution to use standard npm command with grep option instead of custom config
=> Internal: Revert playwright config for Daily Matrix [TMZ-905]

.buildignore, .vscode/settings.json, composer.json, modules/admin-home/assets/js/hello-elementor-conversion-banner.js, modules/admin-home/components/conversion-banner.php, phpcs.xml, tests/bootstrap.php
Purpose: Refactor PLG (Product Lead Generation) conversion banner to display only on specific admin pages with targeted placement.
Main changes:
- Added whitelist of admin pages with custom CSS selectors for banner placement
- Implemented conditional rendering logic with before/after positioning options
- Added constants for script handles, nonce actions, and user meta keys
- Updated JS implementation to use page-specific selectors
=> Tweak: Show PLG only on selected pages [TMZ-919]
